### ISSUE TITLE
The Mystery of the Tower Revealed

### ISSUE THREAD

**Issue by dxnn** [CompSciCabal/SMRTYPRTY#11]
Wand and Friedman 1988
The Mystery of the Tower Revealed: a Non-Reflective Description of the Reflective Tower
https://cs.au.dk/%7Ehosc/local/LaSC-1-1-pp11-37.pdf

**Comment by dxnn** [comment]
Looks like that link is dead for some reason, so maybe get it from here: https://webcache.googleusercontent.com/search?q=cache:OKfFlTFtqo0J:https://cs.au.dk/~hosc/local/LaSC-1-1-pp11-37.pdf+&cd=4&hl=en&ct=clnk&gl=ca&client=safari

Otherwise I'll share my copy in the slack channel.

**Comment by pbevin** [comment]
[TR196.pdf](https://github.com/CompSciCabal/SMRTYPRTY/files/1033487/TR196.pdf)

**Comment by pbevin** [comment]
[TR196.pdf](https://github.com/CompSciCabal/SMRTYPRTY/files/1033488/TR196.pdf)
