### ISSUE TITLE
"Generic programming with C++ concepts and Haskell type classes -- a comparison"

### ISSUE THREAD

**Issue by hzafar** [CompSciCabal/SMRTYPRTY#14]
http://publications.lib.chalmers.se/records/fulltext/local_124669.pdf

**Comment by hzafar** [comment]
Possible "duplicate" of #30 (which looks more interesting).

**Comment by bcdarwin** [comment]
Too bad!  I'm not even sure these two papers were about the same {sort,type,kind,concept} of generics...

**Comment by dxnn** [comment]
Maybe we'll pair them up on consecutive weeks and find out :smile:
