### ISSUE TITLE
Turing Machines: Sets, Logic, and Computation, Chapter 10

### ISSUE THREAD

**Issue by sarostru** [CompSciCabal/SMRTYPRTY#36]
This chapter goes into the details of the Turing machine representation of computation, http://people.ucalgary.ca/~rzach/static/open-logic/courses/phil379/phil379-screen.pdf#page197

**Comment by hzafar** [comment]
That book is beautifully typeset... Also, chapter 11 (on undecidability) might also be interesting to go over.

**Comment by sarostru** [comment]
I was thinking that too, these topics are so deep you can revisit them over and over and always find something new
