### ISSUE TITLE
Hygienic Resugaring of Compositional Desugaring

### ISSUE THREAD

**Issue by hzafar** [CompSciCabal/SMRTYPRTY#61]
https://cs.brown.edu/~sk/Publications/Papers/Published/pk-hyg-resugaring-comp-desugaring/paper.pdf

Saw a reference to this in an issue discussion on the turnstile repo... Looks kind of neat.

**Comment by gregr** [comment]
2015 talk about this: https://www.youtube.com/watch?v=5wPGwkpayoo
